apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-templates
spec:
  templates:
  # Template principal - Orquestador que decide entre Java o Python
  - name: build-administrator
    inputs:
      artifacts:
      - name: clone
        path: /workspace/repo
      parameters:
      - name: lenguaje
      - name: version
    dag:
      tasks:
        - name: build-java
          templateRef:
            name: build-java-templates
            template: build-java
          arguments:
            artifacts:
            - name: clone
              from: "{{inputs.artifacts.clone}}"
            parameters:
            - name: version
              value: "{{inputs.parameters.version}}"
          when: "{{inputs.parameters.lenguaje}} == java"
        
        - name: build-python
          templateRef:
            name: build-python-templates
            template: build-python
          arguments:
            artifacts:
            - name: clone
              from: "{{inputs.artifacts.clone}}"
            parameters:
            - name: version
              value: "{{inputs.parameters.version}}"
          when: "{{inputs.parameters.lenguaje}} == python"
    outputs:
      artifacts:
        - name: build-artifact
          fromExpression: "inputs.parameters.lenguaje == 'java' ? tasks['build-java'].outputs.artifacts['build-artifact'] : tasks['build-python'].outputs.artifacts['build-artifact']"
