apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- configmap.yaml
- git-clone.yaml
- artifact.yaml
- build.yaml
- build-java.yaml
- build-python.yaml
- sonar-validation.yaml

configMapGenerator:
- name: build-scripts
  namespace: argo
  files:
  - scripts/build-java.sh
  - scripts/build-python.sh
  options:
    disableNameSuffixHash: true
